apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: helloprow-go-8lmf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: helloprow-go-8lmf
    app.kubernetes.io/part-of: helloprow-go
  name: helloprow-go-8lmf
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: helloprow-go-8lmf
    weight: 100
status: {}
