apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: helloprow-go-8lmf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: helloprow-go-8lmf
    app.kubernetes.io/part-of: helloprow-go
  name: helloprow-go-8lmf
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: helloprow-go-8lmf
status:
  loadBalancer: {}
